apiVersion: v1
kind: ConfigMap
metadata:
  name: wsrestorden-configmap
  namespace: dev
data:
  POC_CASSANDRA_KEYSPACE: 'sophospoc'
  POC_CASSANDRA_HOST: 'cassandra'
  POC_CASSANDRA_PORT: '9042'
  POC_CASSANDRA_USERNAME: 'cassandra'
  POC_CASSANDRA_PASSWORD: 'store123'
